### ISSUE TITLE
ExecutorService usage issues prevent clean shutdown

### ISSUE THREAD

**Issue by zutnop** [open-eid/digidoc4j#29]
**PROBLEM 1:** Tomcat web application. After validating 1 bdoc, tomcat fails to do a clean shutdown because there are two non-daemon threads running forever:

```
"pool-5-thread-1" #78 prio=5 os_prio=0 tid=0x00007f3346b55800 nid=0x77c7 waiting on condition [0x00007f3304ff2000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000c5c6d1c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"pool-5-thread-2" #79 prio=5 os_prio=0 tid=0x00007f3346c17000 nid=0x77c8 waiting on condition [0x00007f3304ef1000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000c5c6d1c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None
```

CAUSE: `Container.validate()` ends up in `BDocContainerValidator.startSignatureValidationInParallel(...)`, this calls `threadPoolManager.submit(validationExecutor)`, this calls `ThreadPoolManager.initializeDefaultThreadExecutor()` (because configuration didn't have a threadExecutor instance), and now the `ThreadPoolManager` contains a default-named (very hard to debug!) fixed thread pool with 2 (because my machine has 2 cores) non-daemon threads, which don't ever shut down - they require an implicit `defaultThreadExecutor.shutdown()` call for that.

WORKAROUND: I'm setting my own `threadExecutor` instance into `Configuration`, so that `ThreadPoolManager` wouldn't create it's own.

SOLUTION: Either implement shutdown api/hook/logic/documentation or use "short lived" cached thread pool or something else.

---

**PROBLEM 2:** https://www.pivotaltracker.com/story/show/128498307

CAUSE: DSS library `TSLValidationJob` contains an `Executors.newCachedThreadPool()` with 60 seconds idle timeout. This means that after TSL validation, it takes 60 seconds for this executor service threads to "die". I assume that this is the causes for that bug. `TSLValidationJob` needs to either provide a hook for shutdown or allow getting/setting your own `executorService` or something else.

**Comment by nostneji** [comment]
New shutdown hook (org.digidoc4j.ShutdownHook) will be introduced for shutting down executor services and TSL validation job to provide cleaner application shutdown in case of daemon threads used.

**Comment by naare** [comment]
Description how to use the shutdown hook has been added to Q&A, find it [here](https://github.com/open-eid/digidoc4j/wiki/Questions-&-Answers#the-application-which-is-using-digidoc4j-fails-on-a-clean-shutdown)
