### ISSUE TITLE
digidoc4j-util is broken after removing xalan module from pom.xml

### ISSUE THREAD

**Issue by nostneji** [open-eid/digidoc4j#53]
In commit 1abca6297bd7a96ebf4d8abcfa864395c57af0d2 (at 6.11.2018 10:49) pom.xml was modified and dependencies to **xalan** module removed. But DSS uses this module and signing use case with digidoc4j-util gets now following exception:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/xml/utils/URI$MalformedURIException
        at eu.europa.esig.dss.xades.validation.XAdESSignature.checkSignatureIntegrity(XAdESSignature.java:1303)
        at eu.europa.esig.dss.validation.DefaultAdvancedSignature.getSignatureCryptographicVerification(DefaultAdvancedSignature.java:327)
        at eu.europa.esig.dss.xades.signature.ExtensionBuilder.assertSignatureValid(ExtensionBuilder.java:144)
        at eu.europa.esig.dss.xades.signature.XAdESLevelBaselineT.extendSignatureTag(XAdESLevelBaselineT.java:171)
        at eu.europa.esig.dss.xades.signature.XAdESLevelBaselineLT.extendSignatureTag(XAdESLevelBaselineLT.java:66)
        at eu.europa.esig.dss.xades.signature.XAdESLevelBaselineT.extendSignatures(XAdESLevelBaselineT.java:145)
        at eu.europa.esig.dss.xades.signature.XAdESLevelBaselineT.extendSignatures(XAdESLevelBaselineT.java:78)
        at eu.europa.esig.dss.xades.signature.XAdESService.signDocument(XAdESService.java:129)
        at eu.europa.esig.dss.xades.signature.XAdESService.signDocument(XAdESService.java:151)
        at org.digidoc4j.impl.asic.xades.XadesSigningDssFacade.signDocument(XadesSigningDssFacade.java:119)
        at org.digidoc4j.impl.asic.AsicSignatureBuilder.finalizeSignature(AsicSignatureBuilder.java:119)
        at org.digidoc4j.impl.asic.AsicSignatureBuilder.invokeSigningProcess(AsicSignatureBuilder.java:81)
        at org.digidoc4j.SignatureBuilder.invokeSigning(SignatureBuilder.java:167)
        at org.digidoc4j.main.CommandLineExecutor.invokeSigning(CommandLineExecutor.java:483)
        at org.digidoc4j.main.CommandLineExecutor.signWithPkcs11(CommandLineExecutor.java:476)
        at org.digidoc4j.main.CommandLineExecutor.signContainer(CommandLineExecutor.java:413)
        at org.digidoc4j.main.CommandLineExecutor.processContainer(CommandLineExecutor.java:82)
        at org.digidoc4j.main.DigiDoc4J.execute(DigiDoc4J.java:132)
        at org.digidoc4j.main.DigiDoc4J.run(DigiDoc4J.java:103)
        at org.digidoc4j.main.DigiDoc4J.main(DigiDoc4J.java:51)`

`Caused by: java.lang.ClassNotFoundException: org.apache.xml.utils.URI$MalformedURIException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 20 more`

Please put those modules back :)

**Comment by naare** [comment]
Can you give specific branch  or commit number you tried with? I am able to sign with PKCS11 with both of the branches (master release 2.1.1 and develop) using PKCS11 and digidoc4j utility tool. The utility tool was broken in develop branch (not related to xalan removal) but was fixed with [this commit ](https://github.com/open-eid/digidoc4j/commit/ee8a7e334a8cb5affa5794147b0cd57e25a76633)

**Comment by nostneji** [comment]
I used master branch, built all packages with "mvn clean package -P delivery" and used digidoc4j-util.jar in test mode like this:
`c:\Temp>java -Ddigidoc4j.mode=TEST -jar digidoc4j-util.jar -in test.bdoc -add log.txt text/plain -pkcs11 c:\Temp\opensc-pkcs11.dll ***** 1`
Exception may be dependent what card I used, but there is usage of classes from xalan module in DSS.

**Comment by nostneji** [comment]
Ok, the cleaning of the .m2 repository did the trick. But please tag the code in sd-dss project with corresponding tag "dss-5.2.d4j.4".
