### ISSUE TITLE
keystore files included cannot be opened by jdk7

### ISSUE THREAD

**Issue by savemaxim** [open-eid/digidoc4j#63]
Spent few days setting up digidoc4j on jdk7.
Got always error: keytool error: java.io.IOException: Invalid keystore format

Came out that these files (digidoc4j/digidoc4j/src/main/resources/keystore/*.jks) cannot be opened by jdk7.
Probably they are generated by jdk8.

c:\>C:\dev\java\jdk-7u80-windows-x64\bin\keytool -list -keystore C:\dev\git\digidoc4j\digidoc4j\src\main\resources\keystore\keystore.jks -v
keytool error: java.io.IOException: Invalid keystore format
java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(Unknown Source)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(Unknown Source)
        at java.security.KeyStore.load(Unknown Source)
        at sun.security.tools.KeyTool.doCommands(Unknown Source)
        at sun.security.tools.KeyTool.run(Unknown Source)
        at sun.security.tools.KeyTool.main(Unknown Source)

c:\>C:\dev\java\jdk-8u181-windows-x64\bin\keytool -list -keystore C:\dev\git\digidoc4j\digidoc4j\src\main\resources\keystore\keystore.jks -v
Enter keystore password:

It would be good if project is jdk7 ready "out of the box" as stated in wiki :)

Thank You in advance!

**Comment by naare** [comment]
This is planned for next DD4J release (3.1.0).

**Comment by naare** [comment]
3.1.0 has been released.
