### ISSUE TITLE
Failed to load TSl for country "CountryCode" from "TslUrl"

### ISSUE THREAD

**Issue by isakalinsaz** [open-eid/digidoc4j#78]
We have started to see such error logs in our system since 2020-04-13. 

```
Failed to load TSl for country 'CZ' from 'https://tsl.gov.cz/publ/TSL_CZ.xtsl'
Failed to load TSl for country 'ES' from 'https://sede.minetur.gob.es/Prestadores/TSL/TSL.xml'
Failed to load TSl for country 'IT' from 'https://eidas.agid.gov.it/TL/TSL-IT.xml'
Failed to load TSl for country 'CZ' from 'https://tsl.gov.cz/publ/TSL_CZ.xtsl'
Failed to load TSl for country 'LI' from 'https://www.llv.li/files/ak/xml-llv-ak-tsl.xml'
Failed to load TSl for country 'DK' from 'https://www.digst.dk/TSLDKxml'
Failed to load TSl for country 'RO' from 'https://comunicatii.gov.ro/trustedlist.xml'
Failed to load TSl for country 'LU' from 'https://portail-qualite.public.lu/content/dam/qualite/fr/publications/confiance-numerique/liste-confiance-nationale/tsl-xml/tsl.xml'

```
These exceptions are thrown in **eu.europa.esig.dss.tsl.service.TSLValidationJob**.
We are using the latest digidoc4j version which is 4.0.0.

I am not sure is it directly related with the above issue but sometimes we also see another issue when we try to create a Container instance using by ContainerBuilder and this is our sample usage. 

 `ContainerBuilder. aContainer(). fromStream(new ByteArrayInputStream(data)). build();`

```
Unable to load/parse TSL : File Not Found: /tmp/dss-cache-tsl/FI.xml
eu.europa.esig.dss.model.DSSException: File Not Found: /tmp/dss-cache-tsl/FI.xml
	at eu.europa.esig.dss.model.FileDocument.<init>(FileDocument.java:58)
	at eu.europa.esig.dss.model.FileDocument.<init>(FileDocument.java:44)
	at eu.europa.esig.dss.tsl.service.TSLValidationJob.analyzeCountryPointers(TSLValidationJob.java:479)
	at eu.europa.esig.dss.tsl.service.TSLValidationJob.analyzeLOTLBasedModel(TSLValidationJob.java:327)
	at eu.europa.esig.dss.tsl.service.TSLValidationJob.refresh(TSLValidationJob.java:252)
	at org.digidoc4j.impl.asic.tsl.LazyTslCertificateSource.refreshTsl(LazyTslCertificateSource.java:157)
	at org.digidoc4j.impl.asic.tsl.LazyTslCertificateSource.initTsl(LazyTslCertificateSource.java:149)
	at org.digidoc4j.impl.asic.tsl.LazyTslCertificateSource.refreshIfCacheExpired(LazyTslCertificateSource.java:135)
	at org.digidoc4j.impl.asic.tsl.LazyTslCertificateSource.getCertificateSource(LazyTslCertificateSource.java:141)
	at org.digidoc4j.impl.asic.tsl.LazyTslCertificateSource.getCertificatePool(LazyTslCertificateSource.java:75)
	at org.digidoc4j.impl.asic.tsl.CompoundCertificatePool.getTrustedCertificatePool(CompoundCertificatePool.java:158)
	at org.digidoc4j.impl.asic.tsl.CompoundCertificatePool.getInstance(CompoundCertificatePool.java:42)
	at eu.europa.esig.dss.spi.x509.CommonCertificateSource.addCertificate(CommonCertificateSource.java:90)
	at eu.europa.esig.dss.xades.validation.XAdESCertificateSource.getCertificates(XAdESCertificateSource.java:151)
	at eu.europa.esig.dss.xades.validation.XAdESCertificateSource.getKeyInfoCertificates(XAdESCertificateSource.java:107)
	at eu.europa.esig.dss.xades.validation.XAdESCertificateSource.<init>(XAdESCertificateSource.java:89)
	at eu.europa.esig.dss.xades.validation.XAdESSignature.getCertificateSource(XAdESSignature.java:320)
	at eu.europa.esig.dss.validation.timestamp.AbstractTimestampSource.<init>(AbstractTimestampSource.java:95)
	at eu.europa.esig.dss.xades.validation.XAdESTimestampSource.<init>(XAdESTimestampSource.java:54)
	at eu.europa.esig.dss.xades.validation.XAdESSignature.getTimestampSource(XAdESSignature.java:360)
	at eu.europa.esig.dss.xades.validation.XAdESSignature.getTimestampSource(XAdESSignature.java:100)
	at eu.europa.esig.dss.validation.DefaultAdvancedSignature.getArchiveTimestamps(DefaultAdvancedSignature.java:729)
	at eu.europa.esig.dss.validation.DefaultAdvancedSignature.hasLTAProfile(DefaultAdvancedSignature.java:844)
	at eu.europa.esig.dss.xades.validation.XAdESSignature.isDataForSignatureLevelPresent(XAdESSignature.java:1217)
	at eu.europa.esig.dss.validation.DefaultAdvancedSignature.getDataFoundUpToProfile(DefaultAdvancedSignature.java:260)
	at eu.europa.esig.dss.validation.DefaultAdvancedSignature.getDataFoundUpToLevel(DefaultAdvancedSignature.java:234)
	at org.digidoc4j.impl.asic.xades.XadesSignatureParser.parse(XadesSignatureParser.java:39)
	at org.digidoc4j.impl.asic.AsicSignatureParser.createXadesSignature(AsicSignatureParser.java:43)
	at org.digidoc4j.impl.asic.AsicSignatureParser.parse(AsicSignatureParser.java:38)
	at org.digidoc4j.impl.asic.AsicContainerParser.parseSignatures(AsicContainerParser.java:240)
	at org.digidoc4j.impl.asic.AsicContainerParser.populateParseResult(AsicContainerParser.java:228)
	at org.digidoc4j.impl.asic.AsicContainerParser.read(AsicContainerParser.java:87)
	at org.digidoc4j.ContainerOpener.open(ContainerOpener.java:109)
	at org.digidoc4j.ContainerOpener.open(ContainerOpener.java:94)
	at org.digidoc4j.impl.asic.asice.AsicEContainerBuilder.openContainerFromStream(AsicEContainerBuilder.java:37)
	at org.digidoc4j.ContainerBuilder.build(ContainerBuilder.java:139)
```

**Comment by naare** [comment]
The TSL loading problems are shown because of changes in corresponding countries SSL certificates. Some of them have changed the certificates (using certificates from different CA-s) and in case of Romania their SSL certificate has expired. 

You can read here how to update it: https://github.com/open-eid/digidoc4j/wiki/Questions-&-Answers#tsl-ssl-truststore

The second problem is not related to first error messages. We need to look into it.

**Comment by naare** [comment]
1) We are releasing Digidoc4j 4.0.2 shortly with updated TSL SSL truststore and enabling additional countries for TSL loading (Croatia, Germany nad Greece).

2) This error is thrown when the file has been deleted from /tmp/dss-cache-tsl directory. DSS tries to refresh its in memory TSL status from these files. Our assumption is that some other process/job (not related to Digidoc4j) has deleted the temp folder/files for disk space saving?
