### ISSUE TITLE
Unable to finalize signature - for all types of containers

### ISSUE THREAD

**Issue by vrezhar** [open-eid/digidoc4j#82]
Using digidoc4j 3.0.0 in TEST configuration mode, we are unable to finalize digital signatures
Code sample:
 ```
Configuration ddTestConfiguration = new Configuration(Configuration.Mode.TEST)
    ddTestConfiguration.setTslLocation("https://open-eid.github.io/test-TL/tl-mp-test-EE.xml")
    Container container = ContainerBuilder
            .aContainer("ASICE")
            .withConfiguration(ddTestConfiguration)
            .withDataFile(someDataFile)
            .build()
    X509Certificate certificate = getCertificate()
    DataToSign dataToSign = SignatureBuilder.
            aSignature(container).
            withSigningCertificate(certificate).
            withSignatureProfile(SignatureProfile.LT).
            withSignatureDigestAlgorithm(DigestAlgorithm.SHA256).
            buildDataToSign()
    byte[] signedValue = sign(dataToSign.getDataToSign())
    container.addSignature(dataToSign.finalize(signedValue))//exception occurs on finalize() call

```
Stacktrace as follows:

```
Signing document in DSS failed:java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
Caused by: org.digidoc4j.exceptions.TechnicalException: Got error in signing process:
	at org.digidoc4j.impl.asic.xades.XadesSigningDssFacade.signDocument(XadesSigningDssFacade.java:122)
	at org.digidoc4j.impl.asic.AsicSignatureBuilder.finalizeSignature(AsicSignatureBuilder.java:103)
	at org.digidoc4j.DataToSign.finalize(DataToSign.java:96)
Caused by: eu.europa.esig.dss.DSSException: java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
	at eu.europa.esig.dss.xades.DSSXMLUtils.serializeNode(DSSXMLUtils.java:170)
	at eu.europa.esig.dss.xades.signature.XAdESSignatureBuilder.signDocument(XAdESSignatureBuilder.java:797)
	at eu.europa.esig.dss.xades.signature.XAdESLevelBaselineB.signDocument(XAdESLevelBaselineB.java:91)
	at eu.europa.esig.dss.xades.signature.XAdESService.signDocument(XAdESService.java:118)
	at eu.europa.esig.dss.xades.signature.XAdESService.signDocument(XAdESService.java:148)
	at org.digidoc4j.impl.asic.xades.XadesSigningDssFacade.signDocument(XadesSigningDssFacade.java:119)
	... 106 common frames omitted
Caused by: java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
	at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:574)
	at eu.europa.esig.dss.DomUtils.getSecureTransformerFactory(DomUtils.java:119)
	at eu.europa.esig.dss.DomUtils.getSecureTransformer(DomUtils.java:129)
	at eu.europa.esig.dss.xades.DSSXMLUtils.serializeNode(DSSXMLUtils.java:150)
```
Logs:

```
2020-10-01 19:49:32.429  INFO --- [nio-8080-exec-6] o.d.impl.asic.AsicSignatureBuilder       : Getting data to sign
2020-10-01 19:49:32.441  INFO --- [nio-8080-exec-6] e.e.e.d.v.CommonCertificateVerifier      : + New CommonCertificateVerifier created.
2020-10-01 19:49:32.487  INFO --- [nio-8080-exec-6] org.digidoc4j.Configuration              : Source by country <EE> not found, using default TSP source
2020-10-01 19:49:32.579  WARN --- [nio-8080-exec-6] e.e.e.d.s.BaselineBCertificateSelector   : Issuer not found for certificate 85DB0B4E6E1A68529A18CC05E9FBC7E6F5A688C0419D3087DE46DAF938D8FA91
2020-10-01 19:49:58.470  WARN --- [nio-8080-exec-6] o.d.i.asic.xades.XadesSigningDssFacade   : Signing document in DSS failed:java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
```
FYI - We are using MobileId REST API for signatures/certificates.

**Comment by smartman** [comment]
Can it be because of pom.xml dependency issues? This post has very similar stack trace [https://stackoverflow.com/questions/56147602/getting-not-supported-http-javax-xml-xmlconstants-property-accessexternaldt](https://stackoverflow.com/questions/56147602/getting-not-supported-http-javax-xml-xmlconstants-property-accessexternaldt)

**Comment by naare** [comment]
https://github.com/open-eid/digidoc4j/wiki/Questions-&-Answers#getting-an-illegalargumentexception-from-release-211-onward-or-saxnotrecognizedexception-manifested-in-400-rc1

**Comment by vrezhar** [comment]
Hello, sorry for the delayed response.
No, this does not look like a dependency issue, we don't have conflicting versions of Xalan.
I don't know if this helps or not, but here are the logs after TSL refresh
```
2020-10-05 15:49:15.169  INFO --- [           main] e.e.esig.dss.tsl.service.TSLRepository   : New version of EU TSL is stored in cache
2020-10-05 15:49:16.287  WARN --- [           main] e.e.e.dss.tsl.service.TSLValidationJob   : OJ keystore is out-dated !
2020-10-05 15:49:16.325  INFO --- [pool-3-thread-1] e.e.e.d.v.SignedDocumentValidator        : Validator 'eu.europa.esig.dss.cades.validation.CMSDocumentValidator' is registred
2020-10-05 15:49:16.329  INFO --- [pool-3-thread-1] e.e.e.d.v.SignedDocumentValidator        : Validator 'eu.europa.esig.dss.pades.validation.PDFDocumentValidator' is registred
2020-10-05 15:49:16.345  INFO --- [pool-3-thread-1] e.e.e.d.v.SignedDocumentValidator        : Validator 'eu.europa.esig.dss.asic.validation.ASiCContainerWithCAdESValidator' is registred
2020-10-05 15:49:16.345  INFO --- [pool-3-thread-1] e.e.e.d.v.SignedDocumentValidator        : Validator 'eu.europa.esig.dss.xades.validation.XMLDocumentValidator' is registred
2020-10-05 15:49:16.347  INFO --- [pool-3-thread-1] e.e.e.d.v.SignedDocumentValidator        : Validator 'eu.europa.esig.dss.asic.validation.ASiCContainerWithXAdESValidator' is registred
2020-10-05 15:49:16.603  INFO --- [pool-3-thread-1] e.e.e.d.v.SignedDocumentValidator        : Document validation...
2020-10-05 15:49:16.853  INFO --- [pool-3-thread-1] e.e.e.d.x.v.XAdESCertificateSource       : +XAdESCertificateSource
2020-10-05 15:49:16.872  WARN --- [pool-3-thread-1] e.e.e.d.v.SignatureValidationContext     : Revocation data will not be verified because one of the following: token is selfSigned:true or trusted:true or hasNoIssuer:true
2020-10-05 15:49:16.872  WARN --- [pool-3-thread-1] e.e.e.d.v.SignatureValidationContext     : Hence no corresponding data will be added to the signature
2020-10-05 15:49:16.948  INFO --- [pool-3-thread-1] e.e.e.d.xades.validation.XAdESSignature  : Determining signing certificate from certificate candidates list succeeded
2020-10-05 15:49:17.484  INFO --- [           main] e.e.esig.dss.tsl.service.TSLRepository   : New version of EE_T TSL is stored in cache
2020-10-05 15:49:17.509  INFO --- [pool-3-thread-2] e.e.e.d.v.SignedDocumentValidator        : Document validation...
2020-10-05 15:49:17.521  INFO --- [pool-3-thread-2] e.e.e.d.x.v.XAdESCertificateSource       : +XAdESCertificateSource
2020-10-05 15:49:17.531  WARN --- [pool-3-thread-2] e.e.e.d.v.SignatureValidationContext     : Revocation data will not be verified because one of the following: token is selfSigned:true or trusted:true or hasNoIssuer:true
2020-10-05 15:49:17.531  WARN --- [pool-3-thread-2] e.e.e.d.v.SignatureValidationContext     : Hence no corresponding data will be added to the signature
2020-10-05 15:49:17.551  INFO --- [pool-3-thread-2] e.e.e.d.xades.validation.XAdESSignature  : Determining signing certificate from certificate candidates list succeeded
2020-10-05 15:49:17.602  INFO --- [           main] e.e.esig.dss.tsl.service.TSLRepository   : Nb of loaded trusted lists : 2
2020-10-05 15:49:17.602  INFO --- [           main] e.e.esig.dss.tsl.service.TSLRepository   : Nb of trusted certificates : 12
```

**Comment by vrezhar** [comment]
Thanks for the help, setting javax.xml.transform.TransformerFactory to "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl" solved the issue
